# Generated by Django 4.2 on 2026-08-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingdomain',
            name='reputation_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DomainHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spf_status', models.CharField(default='unknown', max_length=10)),
                ('dkim_status', models.CharField(default='unknown', max_length=10)),
                ('dmarc_status', models.CharField(default='unknown', max_length=10)),
                ('mx_status', models.CharField(default='unknown', max_length=10)),
                ('ptr_status', models.CharField(default='unknown', max_length=10)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='domains.sendingdomain')),
            ],
        ),
    ]
