# Generated by Django 4.2 on 2026-08-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=128)),
                ('quota_bytes', models.PositiveBigIntegerField(default=10737418240)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='domains.sendingdomain')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(fields=('domain', 'local_part'), name='unique_mailbox_per_domain'),
        ),
    ]
