# Generated by Django 4.2 on 2026-08-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='mailboxes.mailbox')),
            ],
        ),
    ]
