# Generated by Django 4.2 on 2026-08-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0001_initial'),
        ('email_delivery', '0003_emailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mailboxes.mailbox'),
        ),
    ]
