# Generated by Django 4.2 on 2026-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_delivery', '0004_emailmessage_mailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('replies', 'Replies'), ('trash', 'Trash')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=998),
        ),
    ]
