# Generated by Django 4.2 on 2026-08-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('bounce', 'Bounce'), ('complaint', 'Complaint'), ('unsubscribe', 'Unsubscribe'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='suppression',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_suppression_per_organization'),
        ),
    ]
